### ISSUE TITLE
Moving plain text password into configuration file to avoid security problems

### ISSUE THREAD

**Issue by Pezhin** [rsun0/GroceryBuddy#15]
**Describe the bug**
The account and password to the database is hard-coded in your code base, which raises security problems.

**To Reproduce**
https://github.com/Davidw1339/GroceryBuddy/blob/master/backend/app.py#L5

**Expected behavior**
The account and password should be stored in a configuration files

**Screenshots**
N/A

**Comment by Pezhin** [comment]
I understand this is an early-stage prototype. Just raise this as there is no real "removing" on github so you might want to change the password in the future.

**Comment by davidenwang** [comment]
Good catch! I realize in our haste to get things up and running we completely overlooked this 😞 . Please don't drop our database in the meantime 😨

**Comment by zclewell** [comment]
Fixed in PR #23
